import { makeFunctionReference, type FunctionReference } from "convex/server";
import { createActionProxyTool, type ExecuteProxyToolArgs } from "../action_proxy";
import type { ToolResult } from "../registry";

type SlackToolName =
  | "slack_search_messages"
  | "slack_search_users"
  | "slack_search_channels"
  | "slack_send_message"
  | "slack_send_message_draft"
  | "slack_schedule_message"
  | "slack_read_channel"
  | "slack_read_thread"
  | "slack_create_canvas"
  | "slack_update_canvas"
  | "slack_read_canvas"
  | "slack_read_user_profile";

const executeSlackToolRef = makeFunctionReference<
  "action",
  ExecuteProxyToolArgs<SlackToolName>,
  ToolResult
>("tools/slack/actions:executeSlackTool") as unknown as FunctionReference<
  "action",
  "internal",
  ExecuteProxyToolArgs<SlackToolName>,
  ToolResult
>;

export const slackSearchMessages = createActionProxyTool(executeSlackToolRef, "slack_search_messages", { name: "slack_search_messages", description: "Search messages and files in the user's Slack workspace. Supports Slack search modifiers (from:@user, in:#channel, has:link, before:YYYY-MM-DD, after:YYYY-MM-DD) and semantic queries. Set include_private=false to restrict to public channels only.", parameters: {"type":"object","properties":{"query":{"type":"string","description":"Search query. Supports modifiers: in:#channel, from:@user, has:link, before:YYYY-MM-DD."},"include_private":{"type":"boolean","description":"When true (default), searches public + private channels, DMs, and group DMs. When false, public channels only."},"channel_types":{"type":"string","description":"Only used when include_private=true. Comma-separated subset of: public_channel, private_channel, mpim, im."},"content_types":{"type":"string","description":"Comma-separated: 'messages' and/or 'files'."},"context_channel_id":{"type":"string","description":"Optional channel ID to boost relevance for that channel."},"cursor":{"type":"string","description":"Pagination cursor."},"limit":{"type":"number","description":"Max results (1-20, default 20)."},"after":{"type":"string","description":"Unix timestamp lower bound (inclusive)."},"before":{"type":"string","description":"Unix timestamp upper bound (inclusive)."},"include_bots":{"type":"boolean","description":"Include bot messages (default false)."},"sort":{"type":"string","description":"'score' (default) or 'timestamp'."},"sort_dir":{"type":"string","description":"'asc' or 'desc'."},"response_format":{"type":"string","description":"'detailed' (default) or 'concise'."},"include_context":{"type":"boolean","description":"Include surrounding context messages (default true)."},"max_context_length":{"type":"number","description":"Max chars per context message."}},"required":["query"],"additionalProperties":false} });

export const slackSearchUsers = createActionProxyTool(executeSlackToolRef, "slack_search_users", { name: "slack_search_users", description: "Search Slack users by name, email, department, role, title. Space-separated terms = AND. Use to resolve a user name to an ID (U...).", parameters: {"type":"object","properties":{"query":{"type":"string","description":"Full name, partial name, email, or attribute keywords."},"cursor":{"type":"string","description":"Pagination cursor."},"limit":{"type":"number","description":"Max results (1-20, default 20)."},"response_format":{"type":"string","description":"'detailed' or 'concise'."}},"required":["query"],"additionalProperties":false} });

export const slackSearchChannels = createActionProxyTool(executeSlackToolRef, "slack_search_channels", { name: "slack_search_channels", description: "Search Slack channels by name/description. Returns IDs, names, topics, purposes. Use this first to resolve a channel name like '#general' to an ID (C...).", parameters: {"type":"object","properties":{"query":{"type":"string","description":"Name/description keywords."},"channel_types":{"type":"string","description":"Comma-separated: public_channel, private_channel (default: public_channel)."},"cursor":{"type":"string","description":"Pagination cursor."},"limit":{"type":"number","description":"Max results (1-20, default 20)."},"response_format":{"type":"string","description":"'detailed' or 'concise'."},"include_archived":{"type":"boolean","description":"Include archived channels (default false)."}},"required":["query"],"additionalProperties":false} });

export const slackSendMessage = createActionProxyTool(executeSlackToolRef, "slack_send_message", { name: "slack_send_message", description: "Send a Slack message to a channel or DM. Use a channel ID (C...) or a user ID (U...) for DMs. Supports Slack-flavored markdown. For thread replies pass thread_ts. Find channel/user IDs via slack_search_channels / slack_search_users first.", parameters: {"type":"object","properties":{"channel_id":{"type":"string","description":"Channel ID (e.g. C0123456789) or user ID (U...) for DMs. Use slack_search_channels to resolve names to IDs."},"message":{"type":"string","description":"Message body, up to 5000 chars. Supports markdown (**bold**, _italic_, `code`, lists, links)."},"thread_ts":{"type":"string","description":"Parent message ts value to reply in a thread."},"reply_broadcast":{"type":"boolean","description":"When replying in a thread, also broadcast the reply to the channel."}},"required":["channel_id","message"],"additionalProperties":false} });

export const slackSendMessageDraft = createActionProxyTool(executeSlackToolRef, "slack_send_message_draft", { name: "slack_send_message_draft", description: "Create a draft Slack message attached to a channel (saved in the user's Drafts & Sent, not sent). Use this when the user wants to review before posting. Only one attached draft per channel.", parameters: {"type":"object","properties":{"channel_id":{"type":"string","description":"Channel ID (C...) or user ID (U...) for DMs."},"message":{"type":"string","description":"Draft body in standard markdown."},"thread_ts":{"type":"string","description":"Parent message ts to draft a thread reply."}},"required":["channel_id","message"],"additionalProperties":false} });

export const slackScheduleMessage = createActionProxyTool(executeSlackToolRef, "slack_schedule_message", { name: "slack_schedule_message", description: "Schedule a Slack message for future delivery. post_at is a Unix timestamp at least 2 minutes in the future, max 120 days out. Cannot schedule in Slack Connect channels.", parameters: {"type":"object","properties":{"channel_id":{"type":"string","description":"Channel ID (C...) or user ID (U...) for DMs."},"message":{"type":"string","description":"Message body in markdown."},"post_at":{"type":"number","description":"Unix timestamp in seconds (>= now + 120s, <= now + 120 days)."},"thread_ts":{"type":"string","description":"Parent message ts for a thread reply."},"reply_broadcast":{"type":"boolean","description":"Broadcast the thread reply back to the channel."}},"required":["channel_id","message","post_at"],"additionalProperties":false} });

export const slackReadChannel = createActionProxyTool(executeSlackToolRef, "slack_read_channel", { name: "slack_read_channel", description: "Read messages from a Slack channel in reverse chronological order (newest first). Pass a user_id as channel_id to read DM history. Read-only.", parameters: {"type":"object","properties":{"channel_id":{"type":"string","description":"Channel ID (C...), private group, IM, or user ID for DMs."},"limit":{"type":"number","description":"Number of messages (1-100, default 100)."},"oldest":{"type":"string","description":"Start of time range (Slack ts string)."},"latest":{"type":"string","description":"End of time range (Slack ts string)."},"cursor":{"type":"string","description":"Pagination cursor from a previous response."},"response_format":{"type":"string","description":"'detailed' (default) or 'concise'."}},"required":["channel_id"],"additionalProperties":false} });

export const slackReadThread = createActionProxyTool(executeSlackToolRef, "slack_read_thread", { name: "slack_read_thread", description: "Read a full Slack thread (parent message plus all replies). Requires channel_id and message_ts of the parent message. Read-only.", parameters: {"type":"object","properties":{"channel_id":{"type":"string","description":"Channel ID where the thread lives."},"message_ts":{"type":"string","description":"Timestamp of the parent message (ts value)."},"limit":{"type":"number","description":"Number of messages (1-1000, default 100)."},"cursor":{"type":"string","description":"Pagination cursor."},"oldest":{"type":"string","description":"Start of time range (ts)."},"latest":{"type":"string","description":"End of time range (ts)."},"response_format":{"type":"string","description":"'detailed' (default) or 'concise'."}},"required":["channel_id","message_ts"],"additionalProperties":false} });

export const slackCreateCanvas = createActionProxyTool(executeSlackToolRef, "slack_create_canvas", { name: "slack_create_canvas", description: "Create a Slack Canvas document from Canvas-flavored markdown. Not available on free teams. NOTE: Slack does not accept a channel param here — share the returned canvas URL separately.", parameters: {"type":"object","properties":{"title":{"type":"string","description":"Canvas title (do not repeat in content)."},"content":{"type":"string","description":"Canvas-flavored markdown. Standard headings/lists/links. For user/channel refs use ![](@U123...) and ![](#C123...) syntax. See Slack Canvas formatting docs."}},"required":["title","content"],"additionalProperties":false} });

export const slackUpdateCanvas = createActionProxyTool(executeSlackToolRef, "slack_update_canvas", { name: "slack_update_canvas", description: "Update an existing Slack Canvas. action is one of append|prepend|replace. DANGER: action='replace' WITHOUT section_id overwrites the ENTIRE canvas. Call slack_read_canvas first to get a section_id when replacing a specific section.", parameters: {"type":"object","properties":{"canvas_id":{"type":"string","description":"Canvas ID (e.g. F0123ABC456)."},"action":{"type":"string","description":"'append' (default), 'prepend', or 'replace'."},"content":{"type":"string","description":"Canvas-flavored markdown to insert/replace."},"section_id":{"type":"string","description":"Optional section ID from slack_read_canvas. Strongly recommended with action=replace."}},"required":["canvas_id","action","content"],"additionalProperties":false} });

export const slackReadCanvas = createActionProxyTool(executeSlackToolRef, "slack_read_canvas", { name: "slack_read_canvas", description: "Read a Slack Canvas as markdown, including section_id_mapping used for targeted updates.", parameters: {"type":"object","properties":{"canvas_id":{"type":"string","description":"Canvas ID."}},"required":["canvas_id"],"additionalProperties":false} });

export const slackReadUserProfile = createActionProxyTool(executeSlackToolRef, "slack_read_user_profile", { name: "slack_read_user_profile", description: "Read a Slack user's profile (name, title, email, status, timezone, org, role). Omit user_id to read the current user.", parameters: {"type":"object","properties":{"user_id":{"type":"string","description":"Slack user ID (U...). Defaults to current user when omitted."},"include_locale":{"type":"boolean","description":"Include locale info (default false)."},"response_format":{"type":"string","description":"'detailed' (default) or 'concise'."}},"required":[],"additionalProperties":false} });
