import { defineTable } from "convex/server";
import { v } from "convex/values";

export const cachedModelsTable = defineTable({
  modelId: v.string(),
  name: v.string(),
  description: v.optional(v.string()),
  provider: v.optional(v.string()),
  contextLength: v.optional(v.number()),
  maxCompletionTokens: v.optional(v.number()),
  inputPricePer1M: v.optional(v.number()),
  outputPricePer1M: v.optional(v.number()),
  supportsImages: v.optional(v.boolean()),
  supportsTools: v.optional(v.boolean()),
  supportedParameters: v.optional(v.array(v.string())),
  supportedVoices: v.optional(v.array(v.string())),
  architecture: v.optional(v.object({
    tokenizer: v.optional(v.string()),
    instructType: v.optional(v.string()),
    modality: v.optional(v.string()),
  })),
  canonicalSlug: v.optional(v.string()),
  supportsVideo: v.optional(v.boolean()),
  videoCapabilities: v.optional(v.object({
    supportedResolutions: v.array(v.string()),
    supportedAspectRatios: v.array(v.string()),
    supportedDurations: v.array(v.number()),
    supportedFrameImages: v.array(v.string()),
    supportedSizes: v.array(v.string()),
    generateAudio: v.boolean(),
    seed: v.boolean(),
    pricingSkus: v.optional(v.object({
      videoTokens: v.optional(v.string()),
      videoTokensWithoutAudio: v.optional(v.string()),
      perVideoSecond: v.optional(v.string()),
      perVideoSecond1080p: v.optional(v.string()),
    })),
    pricingSkusMap: v.optional(v.record(v.string(), v.string())),
    allowedPassthroughParameters: v.optional(v.array(v.string())),
    syncedAt: v.number(),
  })),
  imageCapabilities: v.optional(v.object({
    isAvailable: v.optional(v.boolean()),
    pricePerImage: v.optional(v.number()),
    pricePerMegapixel: v.optional(v.number()),
    pricingSkus: v.optional(v.object({
      imageToken: v.optional(v.string()),
      imageOutput: v.optional(v.string()),
    })),
    supportedParameters: v.optional(v.record(v.string(), v.object({
      type: v.optional(v.string()),
      values: v.optional(v.array(v.string())),
      min: v.optional(v.number()),
      max: v.optional(v.number()),
    }))),
    supportsStreaming: v.optional(v.boolean()),
    maxInputReferences: v.optional(v.number()),
    allowedPassthroughParameters: v.optional(v.array(v.string())),
    pricing: v.optional(v.array(v.object({
      billable: v.string(),
      unit: v.string(),
      costUsd: v.number(),
      variant: v.optional(v.string()),
    }))),
    // Retained for future endpoint-aware routing. The model-level descriptor
    // above is the conservative intersection exposed to current clients.
    endpoints: v.optional(v.array(v.object({
      providerName: v.optional(v.string()),
      providerSlug: v.string(),
      providerTag: v.optional(v.union(v.string(), v.null())),
      supportedParameters: v.record(v.string(), v.object({
        type: v.optional(v.string()),
        values: v.optional(v.array(v.string())),
        min: v.optional(v.number()),
        max: v.optional(v.number()),
      })),
      allowedPassthroughParameters: v.array(v.string()),
      supportsStreaming: v.boolean(),
      pricing: v.array(v.object({
        billable: v.string(),
        unit: v.string(),
        costUsd: v.number(),
        variant: v.optional(v.string()),
      })),
    }))),
    managedByImageSync: v.boolean(),
    syncedAt: v.number(),
  })),
  hasZdrEndpoint: v.optional(v.boolean()),
  lastSyncedAt: v.number(),
  benchmarkLlm: v.optional(v.object({
    source: v.literal("artificial_analysis"),
    externalId: v.string(),
    slug: v.string(),
    creatorSlug: v.optional(v.string()),
    creatorName: v.optional(v.string()),
    intelligenceIndex: v.optional(v.number()),
    codingIndex: v.optional(v.number()),
    mathIndex: v.optional(v.number()),
    agenticIndex: v.optional(v.number()),
    speedTokensPerSecond: v.optional(v.number()),
    timeToFirstTokenSeconds: v.optional(v.number()),
    aaInputPricePer1M: v.optional(v.number()),
    aaOutputPricePer1M: v.optional(v.number()),
    aaBlendedPricePer1M: v.optional(v.number()),
    syncedAt: v.number(),
  })),
  benchmarkMedia: v.optional(v.object({
    textToImage: v.optional(v.object({
      source: v.literal("artificial_analysis"),
      externalId: v.string(),
      slug: v.string(),
      elo: v.optional(v.number()),
      rank: v.optional(v.number()),
      releaseDate: v.optional(v.string()),
      syncedAt: v.number(),
    })),
  })),
  openRouterUseCases: v.optional(v.array(v.object({
    category: v.string(),
    returnedRank: v.number(),
    syncedAt: v.number(),
  }))),
  guidanceMatch: v.optional(v.object({
    source: v.literal("artificial_analysis"),
    strategy: v.union(
      v.literal("manual"),
      v.literal("exact_slug"),
      v.literal("canonical_slug_minus_date"),
      v.literal("display_name_exact"),
      v.literal("family_plus_variant_resolution"),
      v.literal("canonical_family"),
      v.literal("normalized_name"),
    ),
    confidence: v.number(),
  })),
  derivedGuidance: v.optional(v.object({
    labels: v.array(v.string()),
    primaryLabel: v.optional(v.string()),
    supportedIntents: v.array(v.string()),
    scores: v.object({
      recommended: v.optional(v.number()),
      coding: v.optional(v.number()),
      research: v.optional(v.number()),
      fast: v.optional(v.number()),
      value: v.optional(v.number()),
      image: v.optional(v.number()),
    }),
    ranks: v.optional(v.object({
      recommended: v.optional(v.number()),
      coding: v.optional(v.number()),
      research: v.optional(v.number()),
      fast: v.optional(v.number()),
      value: v.optional(v.number()),
      image: v.optional(v.number()),
    })),
    totalRanked: v.optional(v.number()),
    lastDerivedAt: v.number(),
  })),
})
  .index("by_modelId", ["modelId"])
  .index("by_provider", ["provider"]);
