import type { ToolEffectPolicy } from "./effect_policy";

const READ: ToolEffectPolicy = { effect: "read", retry: "safe" };
// No production provider adapter currently forwards and verifies the journal's
// stable key. Writes therefore remain non-retriable even though the key is
// exposed in ToolExecutionContext for adapters to adopt deliberately later.
const WRITE: ToolEffectPolicy = { effect: "write", retry: "never" };
const DESTRUCTIVE: ToolEffectPolicy = { effect: "destructive", retry: "never" };

/**
 * Explicit retry/effect inventory for every production tool name.
 *
 * Unknown tools are rejected at registration. This prevents a newly added
 * provider write from silently inheriting a name-based retry policy.
 */
export const TOOL_EFFECT_POLICIES: Readonly<Record<string, ToolEffectPolicy>> = {
  apple_calendar_create: WRITE,
  apple_calendar_delete: DESTRUCTIVE,
  apple_calendar_list: READ,
  apple_calendar_update: WRITE,
  assign_skill_to_persona: WRITE,
  cloze_about_me: READ,
  cloze_add_note: WRITE,
  cloze_add_todo: WRITE,
  cloze_person_add: WRITE,
  cloze_person_change: WRITE,
  cloze_person_count: READ,
  cloze_person_find: READ,
  cloze_project_change: WRITE,
  cloze_project_find: READ,
  cloze_save_draft: WRITE,
  cloze_timeline: READ,
  create_persona: WRITE,
  create_presentation: WRITE,
  create_scheduled_job: WRITE,
  create_skill: WRITE,
  data_python_exec: WRITE,
  data_python_sandbox: WRITE,
  delete_persona: DESTRUCTIVE,
  delete_scheduled_job: DESTRUCTIVE,
  delete_skill: DESTRUCTIVE,
  disable_skill_for_chat: WRITE,
  drive_list: READ,
  drive_move: WRITE,
  drive_read: READ,
  drive_upload: WRITE,
  edit_docx: WRITE,
  edit_pdf: WRITE,
  edit_pptx: WRITE,
  edit_presentation: WRITE,
  edit_xlsx: WRITE,
  enable_skill_for_chat: WRITE,
  fetch_image: READ,
  find_in_document: READ,
  generate_docx: WRITE,
  generate_eml: WRITE,
  generate_pdf: WRITE,
  generate_pptx: WRITE,
  generate_text_file: WRITE,
  generate_xlsx: WRITE,
  gmail_create_draft: WRITE,
  gmail_delete: DESTRUCTIVE,
  gmail_list_labels: READ,
  gmail_modify_labels: WRITE,
  gmail_read: READ,
  gmail_search: READ,
  gmail_send: WRITE,
  google_calendar_create: WRITE,
  google_calendar_delete: DESTRUCTIVE,
  google_calendar_list: READ,
  list_documents: READ,
  list_scheduled_jobs: READ,
  list_skills: READ,
  load_skill: READ,
  ms_calendar_create: WRITE,
  ms_calendar_delete: DESTRUCTIVE,
  ms_calendar_list: READ,
  notion_create_page: WRITE,
  notion_delete_page: DESTRUCTIVE,
  notion_query_database: READ,
  notion_read_page: READ,
  notion_search: READ,
  notion_update_database_entry: WRITE,
  notion_update_page: WRITE,
  onedrive_list: READ,
  onedrive_move: WRITE,
  onedrive_read: READ,
  onedrive_upload: WRITE,
  outlook_delete: DESTRUCTIVE,
  outlook_list_folders: READ,
  outlook_move: WRITE,
  outlook_read: READ,
  outlook_search: READ,
  outlook_send: WRITE,
  propose_docx_edits: WRITE,
  read_document: READ,
  read_docx: READ,
  read_eml: READ,
  read_pdf: READ,
  read_pptx: READ,
  read_presentation: READ,
  read_text_file: READ,
  read_xlsx: READ,
  remove_skill_from_persona: WRITE,
  search_chats: READ,
  slack_create_canvas: WRITE,
  slack_read_canvas: READ,
  slack_read_channel: READ,
  slack_read_thread: READ,
  slack_read_user_profile: READ,
  slack_schedule_message: WRITE,
  slack_search_channels: READ,
  slack_search_messages: READ,
  slack_search_public: READ,
  slack_search_public_and_private: READ,
  slack_search_users: READ,
  slack_send_message: WRITE,
  slack_send_message_draft: WRITE,
  slack_update_canvas: WRITE,
  spawn_subagents: WRITE,
  update_scheduled_job: WRITE,
  update_skill: WRITE,
  vm_delete_file: DESTRUCTIVE,
  vm_exec: WRITE,
  vm_export_file: WRITE,
  vm_import_file: WRITE,
  vm_list_files: READ,
  vm_make_dirs: WRITE,
  vm_read_file: READ,
  vm_reset: DESTRUCTIVE,
  vm_write_file: WRITE,
  web_search: READ,
  workspace_exec: WRITE,
  workspace_export_file: WRITE,
  workspace_import_file: WRITE,
  workspace_list_files: READ,
  workspace_make_dirs: WRITE,
  workspace_read_file: READ,
  workspace_reset: DESTRUCTIVE,
  workspace_write_file: WRITE,
};

export function declaredToolEffectPolicy(toolName: string): ToolEffectPolicy {
  const policy = TOOL_EFFECT_POLICIES[toolName];
  if (!policy) throw new Error(`MISSING_TOOL_EFFECT_POLICY:${toolName}`);
  return policy;
}
