// components/chat/GeneratedFilesCard.tsx
// Renders download links for files generated by an assistant message.
// Image files get an inline preview; other files show icon + download link.

import { useState } from "react";
import { useQuery } from "convex/react";
import { Download } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { getFileIconComponent } from "./fileIcons";

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function isImage(mimeType: string): boolean {
  return mimeType.startsWith("image/");
}

/** Inline image preview with expand-on-click lightbox. */
function ImagePreview({ url, filename }: { url: string; filename: string }) {
  const { t } = useTranslation();
  const [expanded, setExpanded] = useState(false);

  return (
    <>
      <button
        onClick={() => setExpanded(true)}
        className="block rounded-lg overflow-hidden border border-border/20 hover:border-border/40 transition-colors cursor-zoom-in"
      >
        <img
          src={url}
          alt={filename}
          className="max-w-xs max-h-48 object-contain bg-surface-2/50"
          loading="lazy"
        />
      </button>

      {/* Lightbox overlay */}
      {expanded && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm cursor-zoom-out"
          onClick={() => setExpanded(false)}
        >
          <img
            src={url}
            alt={filename}
            className="max-w-[90vw] max-h-[85vh] object-contain rounded-lg shadow-2xl"
          />
          <div className="absolute bottom-6 flex items-center gap-3">
            <span className="text-xs text-white/70">{filename}</span>
            <a
              href={url}
              download={filename}
              onClick={(e) => e.stopPropagation()}
              className="text-xs text-primary hover:underline"
            >
              {t("download")}
            </a>
          </div>
        </div>
      )}
    </>
  );
}

export function GeneratedFilesCard({ messageId }: { messageId: Id<"messages"> }) {
  const files = useQuery(api.chat.queries.getGeneratedFilesByMessage, { messageId });
  if (!files?.length) return null;

  const images = files.filter((f) => isImage(f.mimeType) && f.downloadUrl);
  const others = files.filter((f) => !isImage(f.mimeType) || !f.downloadUrl);

  return (
    <div className="mt-2 space-y-2">
      {/* Inline image previews */}
      {images.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {images.map((f) => (
            <div key={f._id} className="space-y-1">
              <ImagePreview url={f.downloadUrl!} filename={f.filename} />
              <div className="flex items-center gap-2 text-[10px] text-muted px-1">
                <span className="truncate max-w-[200px]">{f.filename}</span>
                {f.sizeBytes != null && <span>{formatSize(f.sizeBytes)}</span>}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Non-image file download links */}
      {others.map((f) => (
        <a
          key={f._id}
          href={f.downloadUrl ?? "#"}
          target="_blank"
          rel="noopener noreferrer"
          download={f.filename}
          className="flex items-center gap-3 rounded-xl border border-border/20 bg-surface-2/50 px-3 py-2.5 transition-colors hover:bg-surface-3/50"
        >
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-primary/12 text-primary">
            {(() => {
              const Icon = getFileIconComponent(f.mimeType);
              return <Icon size={18} />;
            })()}
          </div>
          <div className="flex-1 min-w-0">
            <p className="truncate text-sm font-medium text-foreground">{f.filename}</p>
            {f.sizeBytes != null && (
              <p className="text-xs text-muted">{formatSize(f.sizeBytes)}</p>
            )}
          </div>
          <Download size={16} className="text-muted" />
        </a>
      ))}
    </div>
  );
}
