// components/chat/GeneratedFilesCard.tsx
// Renders download links for files generated by an assistant message.
// Image files get an inline preview; other files show icon + download link.

import { useState } from "react";
import { useQuery } from "convex/react";
import type { TFunction } from "i18next";
import { Download } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { safeDownloadUrl } from "./GeneratedFileDownloadUrl";
import { getFileIconComponent } from "./fileIcons";
import { workspaceIconBlockClass, workspaceSurfaceClass } from "@/lib/uiTokens";
import { captureArtifactUsage } from "@/lib/featureAnalytics";

export type GeneratedFileForPreview = {
  _id: string;
  filename: string;
  mimeType: string;
  sizeBytes?: number | null;
  downloadUrl?: string | null;
  documentId?: Id<"documents"> | string;
  documentVersionId?: Id<"documentVersions"> | string;
  presentationProjectId?: string;
  presentationRevision?: number;
  toolName?: string;
};

export type GeneratedFileOpenRequest = {
  file: GeneratedFileForPreview;
};

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function isImage(mimeType: string): boolean {
  return mimeType.startsWith("image/");
}

function opensInDocumentPanel(file: GeneratedFileForPreview, downloadUrl: string | null): boolean {
  if (file.presentationProjectId) return true;
  const name = file.filename.toLowerCase();
  const mimeType = file.mimeType.toLowerCase();
  if (mimeType.includes("pdf") || name.endsWith(".pdf")) return Boolean(downloadUrl);
  if (!file.documentVersionId) return false;
  return (
    mimeType.includes("wordprocessingml") ||
    mimeType.startsWith("text/") ||
    name.endsWith(".docx") ||
    name.endsWith(".txt") ||
    name.endsWith(".md")
  );
}

function fileTypeLabel(mimeType: string, t: TFunction): string {
  if (mimeType.includes("wordprocessingml") || mimeType.includes("msword")) return t("word_document");
  if (mimeType.includes("spreadsheet") || mimeType.includes("excel")) return t("spreadsheet");
  if (mimeType.includes("presentation") || mimeType.includes("powerpoint")) return t("presentation");
  if (mimeType.includes("pdf")) return t("pdf");
  if (mimeType.includes("csv")) return t("csv");
  if (mimeType.startsWith("image/")) return t("image");
  if (mimeType.startsWith("text/")) return t("text_file");
  if (mimeType === "message/rfc822") return t("email");
  return mimeType.split("/").pop() ?? t("file");
}

function fileMetadata(
  file: { mimeType: string; sizeBytes?: number | null; documentId?: unknown; documentVersionId?: unknown },
  t: TFunction,
): string {
  const parts = [
    file.documentId || file.documentVersionId ? t("saved_document") : undefined,
    fileTypeLabel(file.mimeType, t),
    file.sizeBytes != null ? formatSize(file.sizeBytes) : undefined,
  ].filter(Boolean);
  return parts.join(" • ");
}

/** Inline image preview with expand-on-click lightbox. */
function ImagePreview({
  url,
  file,
  messageId,
}: {
  url: string;
  file: GeneratedFileForPreview;
  messageId: Id<"messages">;
}) {
  const { t } = useTranslation();
  const [expanded, setExpanded] = useState(false);
  const filename = file.filename;
  const capture = (action: "opened" | "downloaded") => captureArtifactUsage(action, {
    message_id: String(messageId),
    artifact_id: file._id,
    mime_type: file.mimeType,
    size_bytes: file.sizeBytes ?? null,
    has_document_id: Boolean(file.documentId || file.documentVersionId),
  });

  return (
    <>
      <button
        type="button"
        onClick={() => {
          capture("opened");
          setExpanded(true);
        }}
        className={workspaceSurfaceClass("block overflow-hidden transition-colors hover:border-border/40 cursor-zoom-in")}
      >
        <img
          src={url}
          alt={filename}
          className="max-w-xs max-h-48 object-contain bg-surface-2/50"
          loading="lazy"
        />
      </button>

      {/* Lightbox overlay */}
      {expanded && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm cursor-zoom-out"
          onClick={() => setExpanded(false)}
        >
          <img
            src={url}
            alt={filename}
            className="max-w-[90vw] max-h-[85vh] object-contain rounded-lg shadow-2xl"
          />
          <div className="absolute bottom-6 flex items-center gap-3">
            <span className="text-xs text-white/70">{filename}</span>
            <a
              href={url}
              download={filename}
              onClick={(e) => {
                e.stopPropagation();
                capture("downloaded");
              }}
              className="text-xs text-primary hover:underline"
            >
              {t("download")}
            </a>
          </div>
        </div>
      )}
    </>
  );
}

export function GeneratedFilesCard({
  messageId,
  onOpenFile,
}: {
  messageId: Id<"messages">;
  onOpenFile?: (request: GeneratedFileOpenRequest) => void;
}) {
  const { t } = useTranslation();
  const files = useQuery(api.chat.queries.getGeneratedFilesByMessage, { messageId });
  if (!files?.length) return null;

  const captureArtifact = (action: "opened" | "downloaded", file: GeneratedFileForPreview) => {
    captureArtifactUsage(action, {
      message_id: String(messageId),
      artifact_id: file._id,
      mime_type: file.mimeType,
      size_bytes: file.sizeBytes ?? null,
      has_document_id: Boolean(file.documentId || file.documentVersionId),
    });
  };

  const fileItems = files.map((file) => ({
    file,
    downloadUrl: safeDownloadUrl(file.downloadUrl),
  }));
  const images = fileItems.filter(({ file, downloadUrl }) => isImage(file.mimeType) && downloadUrl);
  const others = fileItems.filter(({ file, downloadUrl }) => !isImage(file.mimeType) || !downloadUrl);

  return (
    <div className="mt-2 space-y-2">
      {/* Inline image previews */}
      {images.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {images.map(({ file: f, downloadUrl }) => (
            <div key={f._id} className="space-y-1">
              <ImagePreview url={downloadUrl!} file={f} messageId={messageId} />
              <div className="flex items-center gap-2 text-[10px] text-muted px-1">
                <span className="truncate max-w-[200px]">{f.filename}</span>
                <span>{fileMetadata(f, t)}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Non-image file download links */}
      {others.map(({ file: f, downloadUrl }) => {
        const canOpenInPanel = Boolean(onOpenFile && opensInDocumentPanel(f, downloadUrl));
        const content = (
          <>
          <div className={workspaceIconBlockClass()}>
            {(() => {
              const Icon = getFileIconComponent(f.mimeType);
              return <Icon size={18} />;
            })()}
          </div>
          <div className="flex-1 min-w-0">
            <p className="truncate text-sm font-medium text-foreground">{f.filename}</p>
            <p className="text-xs text-muted">{fileMetadata(f, t)}</p>
          </div>
          </>
        );
        if (!downloadUrl && !canOpenInPanel) {
          return (
            <div
              key={f._id}
              aria-disabled="true"
              className={workspaceSurfaceClass(
                "flex min-h-[64px] items-center gap-3 px-3 py-2.5 text-muted opacity-70",
              )}
            >
              {content}
            </div>
          );
        }
        if (canOpenInPanel && onOpenFile) {
          return (
            <div
              key={f._id}
              className={workspaceSurfaceClass(
                "flex min-h-[64px] items-center gap-2 px-3 py-2.5 text-foreground transition-colors hover:bg-surface-3/50",
              )}
            >
              <button
                type="button"
                onClick={() => {
                  captureArtifact("opened", f);
                  onOpenFile({ file: { ...f, downloadUrl } });
                }}
                className="flex min-w-0 flex-1 items-center gap-3 text-left"
              >
                {content}
              </button>
              {downloadUrl && !f.presentationProjectId && (
                <a
                  href={downloadUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  download={f.filename}
                  className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-muted transition-colors hover:bg-surface-3 hover:text-foreground"
                  aria-label={t("download_filename", { filename: f.filename })}
                  title={t("download")}
                  onClick={(event) => {
                    event.stopPropagation();
                    captureArtifact("downloaded", f);
                  }}
                >
                  <Download size={16} />
                </a>
              )}
            </div>
          );
        }
        return (
          <a
            key={f._id}
            href={downloadUrl ?? undefined}
            target="_blank"
            rel="noopener noreferrer"
            download={f.filename}
            className={workspaceSurfaceClass(
              "flex min-h-[64px] items-center gap-3 px-3 py-2.5 text-foreground transition-colors hover:bg-surface-3/50",
            )}
            onClick={() => captureArtifact("downloaded", f)}
          >
            {content}
            <Download size={16} className="text-muted" />
          </a>
        );
      })}
    </div>
  );
}
