export const PURGE_TABLES = [
  "researchSearchTasks",
  "researchSearchBatches",
  "searchPhases",
  "analyticsArtifactIntents",
  "analyticsWorkflowRuns",
  "memoryEmbeddings",
  "nodePositions",
  "subagentRuns",
  "subagentBatches",
  "advisorRuns",
  "advisorBatches",
  "sandboxEvents",
  "sandboxArtifacts",
  "sandboxSessions",
  "jobRuns",
  "scheduledJobApiInvocations",
  "scheduledJobTriggerTokens",
  "runtimeCommands",
  "runEvents",
  "runtimeSessionBindings",
  "executionOperations",
  "executionComponentRefs",
  "executionTeardownTasks",
  "executionAttempts",
  "executionRuns",
  "generationContinuations",
  "generationRoundJournal",
  "drivePickerBatches",
  "messageQueryEmbeddings",
  "messageMemoryContexts",
  "videoOutputUploads",
  "videoJobs",
  "generationJobs",
  "streamingMessages",
  "chatParticipants",
  "chatAdvisors",
  "searchContexts",
  "searchSessions",
  "autonomousSessions",
  "modelSettings",
  "memoryRelationships",
  "oauthConnections",
  "deviceTokens",
  "usageRecords",
  "userSecrets",
  "kbUploadSessions",
  "purchaseEntitlements",
  "favorites",
  "integrationRequestGates",
  "userCapabilities",
  "generatedCharts",
  "contextAssemblyLogs",
  "toolMemories",
  "toolExecutionArtifacts",
  "documentEdits",
  "documentEditBatches",
  "documentVersions",
  "presentationSlideCandidates",
  "presentationCuratorTasks",
  "presentationGenerationBatches",
  "presentationGenerationRuns",
  "presentationAssets",
  "presentationSlides",
  "presentationProjects",
  "skills",
  "documents",
  "generatedFiles",
  "generatedMedia",
  "fileAttachments",
  "googleDriveFileGrants",
  "messages",
  "memories",
  "personas",
  "folders",
  "userPreferences",
  "scheduledJobs",
  "chats",
] as const;

export type PurgeTable = (typeof PURGE_TABLES)[number];

const PURGE_TABLE_SET = new Set<string>(PURGE_TABLES);

export function isPurgeTable(value: string): value is PurgeTable {
  return PURGE_TABLE_SET.has(value);
}
