import { captureSettingChanged } from "@/lib/featureAnalytics";

export type SettingArea = Parameters<typeof captureSettingChanged>[0]["setting_area"];

export const CHAT_DEFAULT_SETTING_AREAS: Record<string, SettingArea> = {
  defaultModelId: "model_picker",
  defaultPersonaId: "model_picker",
  titleModelId: "settings",
  defaultTemperature: "chat",
  defaultMaxTokens: "chat",
  includeReasoning: "chat",
  reasoningEffort: "chat",
  webSearchEnabledByDefault: "search_research",
  defaultSearchMode: "search_research",
  defaultSearchComplexity: "search_research",
  subagentsEnabledByDefault: "subagents",
  autoAudioResponse: "audio",
  preferredVoice: "audio",
  defaultAudioSpeed: "audio",
  defaultSpeechSpeed: "audio",
  defaultSpeechOutputFormat: "audio",
  defaultSpeechInstructions: "audio",
  defaultSpeechStyle: "audio",
  defaultSpeechStyleDegree: "audio",
  defaultVideoAspectRatio: "image_video",
  defaultVideoResolution: "image_video",
  defaultVideoDuration: "image_video",
  defaultVideoGenerateAudio: "image_video",
  defaultImageGenerationModelId: "model_picker",
  defaultMusicGenerationModelId: "model_picker",
  defaultSpeechGenerationModelId: "model_picker",
  defaultVideoGenerationModelId: "model_picker",
  defaultImageCount: "image_video",
  defaultImageAspectRatio: "image_video",
  defaultImageResolution: "image_video",
  defaultImageQuality: "image_video",
  defaultImageBackground: "image_video",
  defaultImageOutputFormat: "image_video",
  defaultImageOutputCompression: "image_video",
  zdrEnabled: "settings",
  sendOnEnter: "settings",
};
