import { makeFunctionReference, type FunctionReference } from "convex/server";
import { createActionProxyTool, type ExecuteProxyToolArgs } from "../action_proxy";
import type { ToolResult } from "../registry";

type NotionToolName =
  | "notion_search"
  | "notion_read_page"
  | "notion_create_page"
  | "notion_update_page"
  | "notion_delete_page"
  | "notion_update_database_entry"
  | "notion_query_database";

const executeNotionToolRef = makeFunctionReference<
  "action",
  ExecuteProxyToolArgs<NotionToolName>,
  ToolResult
>("tools/notion/actions:executeNotionTool") as unknown as FunctionReference<
  "action",
  "internal",
  ExecuteProxyToolArgs<NotionToolName>,
  ToolResult
>;

export const notionSearch = createActionProxyTool(executeNotionToolRef, "notion_search", { name: "notion_search", description: "Search the user's Notion workspace for pages and databases by title. Use when the user asks to find a Notion page, look something up in Notion, or check what pages exist. Returns page titles, IDs, and URLs. Use this when the prompt does not already include the exact page or database ID. Only pages shared with the integration during OAuth consent are searchable.", parameters: {"type":"object","properties":{"query":{"type":"string","description":"Search query string. Searches page and database titles. Leave empty to list recently edited pages."},"filter_type":{"type":"string","description":"Filter results by type: 'page' for pages only, 'database' for databases only. Omit to return both."},"max_results":{"type":"number","description":"Maximum number of results to return (default 10, max 25)."}},"required":[],"additionalProperties":false} });

export const notionReadPage = createActionProxyTool(executeNotionToolRef, "notion_read_page", { name: "notion_read_page", description: "Read the content of a Notion page as markdown. Use when the user asks to read, review, summarize, or analyze a Notion page. If the prompt or user already gives the page ID, use it directly. Otherwise, use notion_search first to find the page. Returns the page content as markdown text along with metadata.", parameters: {"type":"object","properties":{"page_id":{"type":"string","description":"Notion page ID (UUID format, from notion_search results). Can be with or without hyphens."}},"required":["page_id"],"additionalProperties":false} });

export const notionCreatePage = createActionProxyTool(executeNotionToolRef, "notion_create_page", { name: "notion_create_page", description: "Create a new Notion page with markdown content. Use when the user asks to create a new page, document, or note in Notion. The page is created under a specified parent page (by ID). If the prompt or user already gives the parent page ID, use it directly. If no parent is specified, or the parent is only described by name, first use notion_search to find a suitable parent page. Supports full markdown syntax: headings, lists, bold, italic, code blocks, links, etc.", parameters: {"type":"object","properties":{"parent_page_id":{"type":"string","description":"ID of the parent page under which to create the new page. Use notion_search to find suitable parent pages."},"title":{"type":"string","description":"Title for the new Notion page."},"markdown":{"type":"string","description":"Markdown content for the page body. Supports headings, lists, bold, italic, code blocks, links, and other standard markdown."}},"required":["parent_page_id","title","markdown"],"additionalProperties":false} });

export const notionUpdatePage = createActionProxyTool(executeNotionToolRef, "notion_update_page", { name: "notion_update_page", description: "Update the content of an existing Notion page using markdown. Use when the user asks to edit, update, append to, or modify a Notion page. If the prompt or user already gives the page ID, use it directly. Otherwise, use notion_search first to find the page. By default replaces all existing content. Set mode to 'append' to add content after the existing content instead.", parameters: {"type":"object","properties":{"page_id":{"type":"string","description":"Notion page ID to update (from notion_search results)."},"markdown":{"type":"string","description":"New markdown content for the page. Supports headings, lists, bold, italic, code blocks, links, etc."},"mode":{"type":"string","description":"Update mode: 'replace' to replace all content (default), 'append' to insert after existing content."}},"required":["page_id","markdown"],"additionalProperties":false} });

export const notionDeletePage = createActionProxyTool(executeNotionToolRef, "notion_delete_page", { name: "notion_delete_page", description: "Archive (move to trash) a Notion page. Use when the user asks to delete, remove, or trash a Notion page. This archives the page (it can be restored from trash in Notion). If the prompt or user already gives the page ID, use it directly. Otherwise, use notion_search first to find the page.", parameters: {"type":"object","properties":{"page_id":{"type":"string","description":"Notion page ID to archive (from notion_search results)."}},"required":["page_id"],"additionalProperties":false} });

export const notionUpdateDatabaseEntry = createActionProxyTool(executeNotionToolRef, "notion_update_database_entry", { name: "notion_update_database_entry", description: "Update properties (fields) on a Notion database entry (row). Use when the user asks to change a Status, check a checkbox, update a date, edit a text field, or modify any property on a database item. If the prompt or user already gives the entry page_id, use it directly. Otherwise, use notion_query_database to find the entry first. and a properties object mapping property names to new values. Example: page_id=\"abc-123\", properties={\"Status\": \"Done\", \"Priority\": \"High\"}. Supports: title, rich_text, number, select, multi_select, date, checkbox, url, email, phone_number, status. For select/status/multi_select, use the exact option name as it appears in the database.", parameters: {"type":"object","properties":{"page_id":{"type":"string","description":"Page ID of the database entry to update (from notion_query_database results)."},"properties":{"type":"object","additionalProperties":true,"description":"A JSON object mapping Notion property names to their new values. Pass EXACTLY the property names as they appear in the database. Examples:\n  {\"Status\": \"Done\"} — set a select/status property\n  {\"Checked\": true} — set a checkbox\n  {\"Priority\": \"High\"} — set a select property\n  {\"Tags\": [\"urgent\", \"review\"]} — set multi_select\n  {\"Due Date\": \"2026-03-15\"} — set a date\n  {\"Notes\": \"Updated text\"} — set a rich_text property\n  {\"Score\": 42} — set a number property\n  {\"Title\": \"New name\"} — rename the entry\nThe tool auto-detects the correct Notion property type from the database schema. Just pass simple values: strings, numbers, booleans, or arrays of strings."}},"required":["page_id","properties"],"additionalProperties":false} });

export const notionQueryDatabase = createActionProxyTool(executeNotionToolRef, "notion_query_database", { name: "notion_query_database", description: "Query a Notion database to list its entries with optional filtering and sorting. Use when the user asks to view, filter, or analyze data in a Notion database/table. If the prompt or user already gives the database ID, use it directly. Otherwise, use notion_search first to find the database. Returns page entries from the database with their property values.", parameters: {"type":"object","properties":{"database_id":{"type":"string","description":"Notion database ID (from notion_search results with type 'database')."},"filter":{"type":"object","description":"Notion filter object (optional). See Notion API docs for filter syntax. Example: { \"property\": \"Status\", \"select\": { \"equals\": \"Done\" } }"},"max_results":{"type":"number","description":"Maximum number of entries to return (default 20, max 50)."}},"required":["database_id"],"additionalProperties":false} });
