import { makeFunctionReference, type FunctionReference } from "convex/server";
import { createActionProxyTool, type ExecuteProxyToolArgs } from "../action_proxy";
import type { ToolResult } from "../registry";

type ClozeToolName =
  | "cloze_person_find"
  | "cloze_person_count"
  | "cloze_person_add"
  | "cloze_person_change"
  | "cloze_add_note"
  | "cloze_add_todo"
  | "cloze_timeline"
  | "cloze_save_draft"
  | "cloze_about_me"
  | "cloze_project_find"
  | "cloze_project_change";

const executeClozeToolRef = makeFunctionReference<
  "action",
  ExecuteProxyToolArgs<ClozeToolName>,
  ToolResult
>("tools/cloze/actions:executeClozeTool") as unknown as FunctionReference<
  "action",
  "internal",
  ExecuteProxyToolArgs<ClozeToolName>,
  ToolResult
>;

export const clozePersonFind = createActionProxyTool(executeClozeToolRef, "cloze_person_find", { name: "cloze_person_find", description: "Search for people in the user's Cloze CRM. Supports free-text queries, stage/segment/step filtering, pagination, and sorting. Returns matching person records with names, emails, phones, stages, segments, and custom fields.", parameters: {"type":"object","properties":{"query":{"type":"string","description":"Free-text search query (same as the Cloze search bar). Searches names, emails, phones, companies, notes."},"stage":{"type":"string","description":"Filter by relationship stage: lead, future, current, past, out, none, any."},"segment":{"type":"string","description":"Filter by segment key or name (e.g. 'customer', 'partner')."},"step":{"type":"string","description":"Filter by step key, or 'none'/'any'."},"assignee":{"type":"string","description":"Filter by assignee email address."},"sort":{"type":"string","description":"Sort order: lastchanged, bestrelationship, firstmet, lasttalked, wentquiet, assigned, duenext, duepast, first, last, nextstep, distance, value, created, start, end, name."},"scope":{"type":"string","description":"Scope: 'local' (your contacts), 'team', or 'hierarchy:/X/Y/Z'."},"page_size":{"type":"number","description":"Results per page (default 10, max 100)."},"page_number":{"type":"number","description":"Page number starting from 1."}},"required":[],"additionalProperties":false} });

export const clozePersonCount = createActionProxyTool(executeClozeToolRef, "cloze_person_count", { name: "cloze_person_count", description: "Count people in the user's Cloze CRM matching given criteria. Faster than a full search when you only need the total. Supports the same filters as cloze_person_find.", parameters: {"type":"object","properties":{"query":{"type":"string","description":"Free-text search query."},"stage":{"type":"string","description":"Filter by stage: lead, future, current, past, out, none, any."},"segment":{"type":"string","description":"Filter by segment key or name."},"step":{"type":"string","description":"Filter by step key, or 'none'/'any'."},"assignee":{"type":"string","description":"Filter by assignee email."},"scope":{"type":"string","description":"Scope: 'local', 'team', or 'hierarchy:/X/Y/Z'."}},"required":[],"additionalProperties":false} });

export const clozePersonAdd = createActionProxyTool(executeClozeToolRef, "cloze_person_add", { name: "cloze_person_add", description: "Add a new person to the user's Cloze CRM. Provide at least a name or email. Can include phone numbers, stage, segment, keywords, custom fields, notes, and more.", parameters: {"type":"object","properties":{"name":{"type":"string","description":"Full name."},"first":{"type":"string","description":"First name."},"last":{"type":"string","description":"Last name."},"emails":{"type":"array","items":{"type":"object"},"description":"Array of email objects: [{\"value\":\"a@b.com\",\"work\":true}]. Flags: work, home, preferred (booleans)."},"phones":{"type":"array","items":{"type":"object"},"description":"Array of phone objects: [{\"value\":\"+15551234\",\"mobile\":true}]. Flags: work, home, mobile (booleans)."},"stage":{"type":"string","description":"Relationship stage: lead, future, current, past, out."},"segment":{"type":"string","description":"Segment key or name."},"step":{"type":"string","description":"Step key."},"headline":{"type":"string","description":"Headline / title."},"keywords":{"type":"array","items":{"type":"string"},"description":"Tags / keywords."},"notes":{"type":"string","description":"About notes (rich-text or plain)."},"assign_to":{"type":"string","description":"Email of team member to assign."},"share_to":{"type":"string","description":"Email to share to, or \"team\" for whole team."},"custom_fields":{"type":"array","items":{"type":"object"},"description":"Array of custom field objects: [{\"id\":\"field-id\",\"type\":\"text\",\"value\":\"val\"}]."}},"required":[],"additionalProperties":false} });

export const clozePersonChange = createActionProxyTool(executeClozeToolRef, "cloze_person_change", { name: "cloze_person_change", description: "Update an existing person in Cloze. Provide enough identifying info (email, phone, or app link) to match, plus the fields to change. Provided fields are merged into the existing record.", parameters: {"type":"object","properties":{"name":{"type":"string","description":"Full name (used for matching if unique)."},"emails":{"type":"array","items":{"type":"object"},"description":"Email objects (used for matching + updating)."},"phones":{"type":"array","items":{"type":"object"},"description":"Phone objects (used for matching + updating)."},"stage":{"type":"string","description":"New stage: lead, future, current, past, out."},"segment":{"type":"string","description":"New segment key or name."},"step":{"type":"string","description":"New step key."},"headline":{"type":"string","description":"New headline / title."},"keywords":{"type":"array","items":{"type":"string"},"description":"Tags to set."},"notes":{"type":"string","description":"About notes to set."},"assign_to":{"type":"string","description":"Email of team member to assign."},"custom_fields":{"type":"array","items":{"type":"object"},"description":"Custom fields to set."},"app_links":{"type":"array","items":{"type":"object"},"description":"External app links for matching: [{\"source\":\"mycrm.com\",\"uniqueid\":\"123\"}]."}},"required":[],"additionalProperties":false} });

export const clozeAddNote = createActionProxyTool(executeClozeToolRef, "cloze_add_note", { name: "cloze_add_note", description: "Add a note to a person, company, or project in Cloze. Notes appear on the timeline. You can reference people/projects so the note is linked to them.", parameters: {"type":"object","properties":{"subject":{"type":"string","description":"Note subject / title."},"body":{"type":"string","description":"Note body text."},"body_type":{"type":"string","description":"'html' or 'text' (default 'text')."},"references":{"type":"array","items":{"type":"object"},"description":"People/companies/projects to link: [{\"value\":\"john@example.com\",\"name\":\"John Doe\"}]."},"source":{"type":"string","description":"Source domain for the note (e.g. 'nanthai.com'). Required."},"unique_id":{"type":"string","description":"Unique ID from your system. Required (prevents duplicates)."},"date":{"type":"string","description":"ISO date/time or UTC ms timestamp. Defaults to now."}},"required":["source","unique_id"],"additionalProperties":false} });

export const clozeAddTodo = createActionProxyTool(executeClozeToolRef, "cloze_add_todo", { name: "cloze_add_todo", description: "Create a to-do / task in Cloze. Can be assigned to a team member and linked to specific people via the participants field.", parameters: {"type":"object","properties":{"subject":{"type":"string","description":"To-do description / title. Required."},"when":{"type":"string","description":"Due date as ISO string, UTC ms timestamp, or '1' for 'someday'. Omit for 'someday'."},"participants":{"type":"array","items":{"type":"string"},"description":"Email/phone of related people."},"assignee":{"type":"string","description":"Email of user to assign the to-do to (default: API caller)."},"assigner":{"type":"string","description":"Email of user creating the assignment (default: API caller)."}},"required":["subject"],"additionalProperties":false} });

export const clozeTimeline = createActionProxyTool(executeClozeToolRef, "cloze_timeline", { name: "cloze_timeline", description: "Get a person's record and recent activity from Cloze. Returns the full person record including name, emails, phones, stage, segment, about notes, and timeline items. Look up by email address or Cloze unique ID.", parameters: {"type":"object","properties":{"email":{"type":"string","description":"Email address of the person to look up."},"unique_id":{"type":"string","description":"Cloze internal unique ID of the person."}},"required":[],"additionalProperties":false} });

export const clozeSaveDraft = createActionProxyTool(executeClozeToolRef, "cloze_save_draft", { name: "cloze_save_draft", description: "Save an email draft in Cloze. Creates an email communication record on the timeline. The draft will appear in the person's timeline.", parameters: {"type":"object","properties":{"to":{"type":"array","items":{"type":"object"},"description":"Recipients: [{\"value\":\"jane@co.com\",\"name\":\"Jane\",\"role\":\"to\"}]. role: 'to', 'cc', or 'bcc'."},"from":{"type":"string","description":"Sender email address."},"subject":{"type":"string","description":"Email subject line."},"body":{"type":"string","description":"Email body."},"body_type":{"type":"string","description":"'html' or 'text' (default 'text')."},"references":{"type":"array","items":{"type":"object"},"description":"People/companies/projects to link the email to."}},"required":["subject","body"],"additionalProperties":false} });

export const clozeAboutMe = createActionProxyTool(executeClozeToolRef, "cloze_about_me", { name: "cloze_about_me", description: "Get the current Cloze user's profile. Returns name, email, phone, address, photo URL, account scopes, and permissions.", parameters: {"type":"object","properties":{},"required":[],"additionalProperties":false} });

export const clozeProjectFind = createActionProxyTool(executeClozeToolRef, "cloze_project_find", { name: "cloze_project_find", description: "Search for projects / deals in the user's Cloze CRM. Supports free-text queries, stage/segment/step filtering, pagination, and sorting. Returns matching project records.", parameters: {"type":"object","properties":{"query":{"type":"string","description":"Free-text search query."},"stage":{"type":"string","description":"Filter by project stage: future, current, won, lost, none, any."},"segment":{"type":"string","description":"Filter by segment key or name."},"step":{"type":"string","description":"Filter by step key, or 'none'/'any'."},"assignee":{"type":"string","description":"Filter by assignee email."},"collaborator":{"type":"string","description":"Filter by deal-team collaborator email."},"scope":{"type":"string","description":"Scope: 'local', 'team', or 'hierarchy:/X/Y/Z'."},"sort":{"type":"string","description":"Sort order: lastchanged, name, value, created, start, end, duenext, duepast, nextstep, assigned, etc."},"hide_lost_done":{"type":"boolean","description":"Hide lost/done projects (default false)."},"page_size":{"type":"number","description":"Results per page (default 10, max 100)."},"page_number":{"type":"number","description":"Page number starting from 1."}},"required":[],"additionalProperties":false} });

export const clozeProjectChange = createActionProxyTool(executeClozeToolRef, "cloze_project_change", { name: "cloze_project_change", description: "Update an existing project / deal in Cloze. Provide the project name (or app link) for matching, plus the fields to change. Fields are merged into the existing project record.", parameters: {"type":"object","properties":{"name":{"type":"string","description":"Project name (used for matching). Required unless app_links provided."},"summary":{"type":"string","description":"Project description / summary."},"stage":{"type":"string","description":"New stage: future, current, won, lost."},"segment":{"type":"string","description":"Segment key or name."},"step":{"type":"string","description":"Step key."},"keywords":{"type":"array","items":{"type":"string"},"description":"Tags / keywords."},"notes":{"type":"string","description":"About notes."},"at_a_glance_notes":{"type":"string","description":"At-a-glance notes."},"start_date":{"type":"string","description":"Project start date (ISO format)."},"end_date":{"type":"string","description":"Project end date (ISO format)."},"project_team":{"type":"array","items":{"type":"string"},"description":"Collaborator email addresses."},"custom_fields":{"type":"array","items":{"type":"object"},"description":"Custom fields to set."},"app_links":{"type":"array","items":{"type":"object"},"description":"External app links for matching: [{\"source\":\"mycrm.com\",\"uniqueid\":\"123\"}]."}},"required":[],"additionalProperties":false} });
